-- Initial schema. Core, indexed columns only; everything that may grow later
-- (time of day, weather, future tags) lives in shots.extra_metadata as JSON.

CREATE TABLE presets (
  id                  TEXT PRIMARY KEY,            -- UUID generated by the client
  name                TEXT NOT NULL,
  sensor_width_mm     REAL NOT NULL,
  sensor_height_mm    REAL NOT NULL,
  speedbooster_factor REAL NOT NULL DEFAULT 1.0,   -- 1.0 = no speedbooster
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE TABLE shots (
  id              TEXT PRIMARY KEY,                -- UUID generated by the client
  timestamp       TEXT NOT NULL,                   -- ISO 8601 UTC, capture time on device
  lat             REAL NOT NULL,
  lon             REAL NOT NULL,
  preset_id       TEXT REFERENCES presets(id) ON DELETE SET NULL,
  lens_mm         REAL NOT NULL,
  r2_object_key   TEXT NOT NULL UNIQUE,
  extra_metadata  TEXT CHECK (extra_metadata IS NULL OR json_valid(extra_metadata)),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX shots_timestamp_idx ON shots (timestamp DESC);
CREATE INDEX shots_preset_idx    ON shots (preset_id);
CREATE INDEX shots_latlon_idx    ON shots (lat, lon);
