-- Baseline schema (2026-09 rework). Replaces the prototype migrations; prototype data was dropped.
-- A shot is the unit of scouting metadata (name, tags, review state); it owns one or more photos.
-- A normal capture makes a shot with one photo, sequence mode makes one shot with many.
-- All ids are UUIDs generated by the client so offline-created rows can be synced later.

CREATE TABLE projects (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  notes       TEXT,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT
);
CREATE UNIQUE INDEX projects_name_idx ON projects (name COLLATE NOCASE);

-- Rigs: camera body + recording format (+ speedbooster). Sensor dimensions are the source of truth for the math.
CREATE TABLE presets (
  id                  TEXT PRIMARY KEY,
  name                TEXT NOT NULL,
  camera_id           TEXT,
  format_id           TEXT,
  sensor_width_mm     REAL NOT NULL,
  sensor_height_mm    REAL NOT NULL,
  speedbooster_factor REAL NOT NULL DEFAULT 1.0,   -- 1.0 = no speedbooster
  lens_min_mm         REAL,                        -- optional lens range (e.g. an 18-35 zoom); NULL = any lens
  lens_max_mm         REAL,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at          TEXT
);

-- Named places, shared by all projects.
CREATE TABLE locations (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT
);
CREATE UNIQUE INDEX locations_name_idx ON locations (name COLLATE NOCASE);

CREATE TABLE shots (
  id           TEXT PRIMARY KEY,
  project_id   TEXT NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  location_id  TEXT REFERENCES locations(id) ON DELETE SET NULL,
  name         TEXT,
  int_ext      TEXT,                                -- int | ext
  light        TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(light) AND json_type(light) = 'array'),  -- subset of dawn, day, dusk, night
  artificial   INTEGER NOT NULL DEFAULT 0,          -- 1 = lit artificially, independent of the daylight phases
  weather      TEXT,
  state        TEXT NOT NULL DEFAULT 'unreviewed',  -- unreviewed | approved | archived
  extra        TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(extra) AND json_type(extra) = 'object'),
  captured_at  TEXT NOT NULL,                       -- capture time of the first photo (ISO 8601 UTC)
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at   TEXT
);
CREATE INDEX shots_captured_idx ON shots (captured_at DESC, id DESC);
CREATE INDEX shots_project_idx  ON shots (project_id);
CREATE INDEX shots_state_idx    ON shots (state);
CREATE INDEX shots_location_idx ON shots (location_id);

CREATE TABLE photos (
  id              TEXT PRIMARY KEY,
  shot_id         TEXT NOT NULL REFERENCES shots(id) ON DELETE CASCADE,
  ordinal         INTEGER NOT NULL,                 -- position inside the shot, 0-based
  timestamp       TEXT NOT NULL,                    -- capture time on device (ISO 8601 UTC)
  lat             REAL NOT NULL,
  lon             REAL NOT NULL,
  gps_accuracy_m  REAL,
  preset_id       TEXT REFERENCES presets(id) ON DELETE SET NULL,
  lens_mm         REAL NOT NULL,
  r2_object_key   TEXT NOT NULL UNIQUE,
  width           INTEGER,                          -- uploaded image size in px
  height          INTEGER,
  framing         TEXT CHECK (framing IS NULL OR json_valid(framing)),  -- rig/lens snapshot incl. frame fractions
  device          TEXT CHECK (device IS NULL OR json_valid(device)),    -- phone model, EXIF focal lengths, GPS extras
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (shot_id, ordinal)
);
CREATE INDEX photos_shot_idx   ON photos (shot_id, ordinal);
CREATE INDEX photos_preset_idx ON photos (preset_id);

-- Saved dashboard filters: a name plus a filter JSON (see @fielder/vocab filter.ts).
CREATE TABLE views (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  filter      TEXT NOT NULL CHECK (json_valid(filter)),
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT
);
