-- Scouting metadata on shots plus a review state, and named locations (a location is in one district).

CREATE TABLE locations (
  id          TEXT PRIMARY KEY,                    -- UUID generated by the client
  name        TEXT NOT NULL,
  district    TEXT NOT NULL,                       -- one of the Berlin boroughs (validated by the Worker)
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT
);
CREATE UNIQUE INDEX locations_name_idx ON locations (name COLLATE NOCASE);

ALTER TABLE shots ADD COLUMN name        TEXT;
ALTER TABLE shots ADD COLUMN light       TEXT;
ALTER TABLE shots ADD COLUMN weather     TEXT;
ALTER TABLE shots ADD COLUMN int_ext     TEXT;
ALTER TABLE shots ADD COLUMN location_id TEXT REFERENCES locations(id) ON DELETE SET NULL;
ALTER TABLE shots ADD COLUMN state       TEXT NOT NULL DEFAULT 'unreviewed';   -- unreviewed | approved | archived

CREATE INDEX shots_state_idx    ON shots (state);
CREATE INDEX shots_location_idx ON shots (location_id);
