-- Saved filter "views" for the dashboard: a name plus a filter JSON (see @fielder/vocab filter.ts).
CREATE TABLE views (
  id          TEXT PRIMARY KEY,                    -- UUID generated by the client
  name        TEXT NOT NULL,
  filter      TEXT NOT NULL CHECK (json_valid(filter)),
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  TEXT
);
