/** The one themed style sheet behind the primitives in this folder (built once per theme, see makeStyles). */
import { BORDER, FIXED, makeStyles, num, RADIUS, SIZE, type } from "./theme";

export const useStyles = makeStyles((c) => ({
  sheetWrap: { flex: 1, justifyContent: "flex-end", alignItems: "center" },
  backdrop: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: c.scrim },
  sheet: { backgroundColor: c.surfaceRaised, borderTopLeftRadius: RADIUS.lg, borderTopRightRadius: RADIUS.lg, borderTopWidth: BORDER.control, borderColor: c.borderStrong, elevation: 12, overflow: "hidden" },
  sheetBody: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 32, gap: 12 },
  sheetFooter: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 32, borderTopWidth: BORDER.control, borderTopColor: c.border, backgroundColor: c.surfaceRaised, gap: 8 },
  grab: { width: 44, height: 5, borderRadius: 3, backgroundColor: c.border, alignSelf: "center", marginTop: 10, marginBottom: 2 },
  sheetHeader: { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 8, paddingBottom: 8, minHeight: 56, borderBottomWidth: 1, borderBottomColor: c.borderSubtle },
  sheetTitle: { ...type("title", "bold"), color: c.text },
  sheetSub: { ...type("caption"), color: c.textDim, ...num },
  headBtn: { minWidth: 64, height: SIZE.touchMin, paddingHorizontal: 12, borderRadius: RADIUS.sm, alignItems: "center", justifyContent: "center" },
  headBtnPressed: { backgroundColor: c.accentTint },
  headBtnText: { ...type("body", "bold"), color: c.accent },
  section: { ...type("overline", "bold"), color: c.textDim },
  row: { paddingVertical: 14, borderTopWidth: 1, borderTopColor: c.borderSubtle },
  rowLabel: { ...type("overline", "bold"), color: c.text, marginBottom: 10 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: { flexDirection: "row", alignItems: "center", gap: 6, minHeight: SIZE.touchMin, paddingHorizontal: 16, borderRadius: RADIUS.pill, borderWidth: BORDER.control, borderColor: c.border, backgroundColor: c.surface },
  chipBlock: { flex: 1, justifyContent: "center" },
  chipPressed: { backgroundColor: c.surfaceSunken, borderColor: c.borderStrong },
  chipSelected: { backgroundColor: c.accent, borderColor: c.accent, paddingLeft: 12 },
  chipDisabled: { borderStyle: "dashed", borderColor: c.textDisabled, backgroundColor: "transparent" },
  chipText: { ...type("label", "medium"), color: c.text, flexShrink: 1 },
  swatch: { width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: c.borderStrong },
  chipTextSelected: { fontFamily: type("label", "bold").fontFamily },
  seg: { flexDirection: "row", alignSelf: "flex-start", padding: 3, gap: 2, borderWidth: BORDER.control, borderColor: c.border, borderRadius: RADIUS.pill, backgroundColor: c.surface },
  segBlock: { alignSelf: "stretch" },
  segOpt: { flexDirection: "row", alignItems: "center", gap: 6, minHeight: 42, minWidth: 48, paddingHorizontal: 14, borderRadius: RADIUS.pill, justifyContent: "center" },
  segOptLg: { minHeight: 44 },
  segText: { ...type("label", "medium"), color: c.text },
  segTextOn: { fontFamily: type("label", "bold").fontFamily, color: c.onAccent },
  input: { ...type("body"), minHeight: SIZE.control, backgroundColor: c.surface, color: c.text, borderWidth: BORDER.control, borderColor: c.border, borderRadius: RADIUS.sm, paddingHorizontal: 14, paddingVertical: 10 },
  inputFocused: { borderColor: c.accent },
  btn: { flexDirection: "row", gap: 8, minHeight: SIZE.control, paddingHorizontal: 16, borderRadius: RADIUS.sm, borderWidth: BORDER.control, alignItems: "center", justifyContent: "center" },
  btnBig: { flex: 1, flexDirection: "column", gap: 6 },
  btnDisabled: { backgroundColor: "transparent", borderStyle: "dashed", borderColor: c.textDisabled },
  btnText: { ...type("body", "semibold"), flexShrink: 1 },
  btnTextBig: { ...type("title", "bold"), textAlign: "center" },
  iconBtn: { borderRadius: RADIUS.sm, borderWidth: BORDER.control, borderColor: c.border, alignItems: "center", justifyContent: "center", backgroundColor: c.surface },
  state: { flexDirection: "row", alignItems: "center", gap: 4, alignSelf: "flex-start", height: 26, paddingLeft: 6, paddingRight: 8, borderRadius: RADIUS.xs, borderWidth: 1.5 },
  stateLg: { height: 32, paddingLeft: 8, paddingRight: 10 },
  stateIcon: { width: 26, paddingLeft: 0, paddingRight: 0, justifyContent: "center", borderRadius: 13, borderColor: FIXED.black },
  stateText: { ...type("caption", "bold"), fontSize: 12, letterSpacing: 0.6, textTransform: "uppercase" },
  seq: { flexDirection: "row", alignItems: "center", gap: 5, alignSelf: "flex-start", height: 26, paddingHorizontal: 8, borderRadius: RADIUS.xs, backgroundColor: FIXED.black, borderWidth: 1, borderColor: "rgba(255,255,255,0.55)" },
  seqRec: { backgroundColor: FIXED.record, borderColor: FIXED.white, borderWidth: 2, height: 34, paddingHorizontal: 12, borderRadius: 6 },
  seqDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: FIXED.white },
  seqText: { ...type("caption", "heavy"), color: FIXED.white, letterSpacing: 0.5, ...num },
  photoTag: { height: 32, paddingHorizontal: 10, borderRadius: RADIUS.xs, backgroundColor: FIXED.black, alignItems: "center", justifyContent: "center" },
  photoTagText: { ...type("small", "heavy"), color: FIXED.white, ...num },
  hint: { ...type("caption"), color: c.textDim },
  toggleRow: { flexDirection: "row", alignItems: "center", gap: 14, minHeight: 64, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: c.surface, borderBottomWidth: 1, borderBottomColor: c.borderSubtle },
  toggleLabel: { ...type("body", "semibold"), color: c.text },
  track: { width: 52, height: 30, borderRadius: RADIUS.pill, borderWidth: BORDER.control, borderColor: c.border, backgroundColor: c.surfaceSunken, justifyContent: "center" },
  knob: { position: "absolute", width: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  check: { width: 28, height: 28, borderRadius: RADIUS.xs + 2, borderWidth: BORDER.control, borderColor: c.border, alignItems: "center", justifyContent: "center", backgroundColor: c.surface },
  listRow: { flexDirection: "row", alignItems: "center", gap: 14, minHeight: 64, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: c.surface, borderBottomWidth: 1, borderBottomColor: c.borderSubtle },
  listRowOn: { backgroundColor: c.accentTint },
  listTitle: { ...type("body", "semibold"), color: c.text },
  listTitleOn: { fontFamily: type("body", "heavy").fontFamily },
  listMeta: { ...type("small"), color: c.textDim, ...num },
  banner: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 52, paddingHorizontal: 12, paddingVertical: 8, borderWidth: BORDER.control, borderRadius: RADIUS.sm },
  bannerTitle: { ...type("small", "bold"), color: c.text },
  bannerMeta: { ...type("caption"), color: c.textDim },
  empty: { alignItems: "center", gap: 8, paddingVertical: 40, paddingHorizontal: 24 },
  emptyIcon: { width: 56, height: 56, borderRadius: 28, borderWidth: BORDER.control, borderColor: c.border, alignItems: "center", justifyContent: "center", marginBottom: 4 },
  emptyTitle: { ...type("title", "bold"), color: c.text, textAlign: "center" },
  emptyBody: { ...type("small"), color: c.textDim, textAlign: "center", maxWidth: 340 },
}));
